app = "navidrome-server"
primary_region = "fra"

[build]
  image = "deluan/navidrome:latest"

[[mounts]]
  source = "data"
  destination = "/data"

[http_service]
  internal_port = 4533
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true